version: "3"
services:
  app:
      build: .
      container_name: simple-grpc-go 
      ports:
        - 8080:8080
      depends_on:
        - mysql
        - redis
      networks:
        - fullstack
  mysql:
      container_name: mysql
      image: mysql:5.7.33
      environment:
        - MYSQL_ROOT_PASSWORD=password
      ports:
        - 3307:3306

networks:
  fullstack:
    driver: bridge